Example1Form:= TExample1Form.Create; 
InitFormObject(Example1Form,'Example1Form');
Example1Form.MyRootDiv:= TXScrollBox(CreateInterfaceObject(Example1Form,'TXScrollBox','MyRootDiv'));
Example1Form.XEditBox1:= TXEditBox(CreateInterfaceObject(Example1Form,'TXEditBox','XEditBox1'));

Example1Form.XCheckBox1:= TXCheckBox(CreateInterfaceObject(Example1Form,'TXCheckBox','XCheckBox1'));

Example1Form.XHyperLink1:= TXHyperlink(CreateInterfaceObject(Example1Form,'TXHyperlink','XHyperLink1'));

Example1Form.XHBox1:= TXHBox(CreateInterfaceObject(Example1Form,'TXHBox','XHBox1'));
Example1Form.XButton2:= TXButton(CreateInterfaceObject(Example1Form,'TXButton','XButton2'));

Example1Form.XButton1:= TXButton(CreateInterfaceObject(Example1Form,'TXButton','XButton1'));


Example1Form.XTabControl1:= TXTabControl(CreateInterfaceObject(Example1Form,'TXTabControl','XTabControl1'));
Example1Form.XTabSheet1:= TXTabSheet(CreateInterfaceObject(Example1Form,'TXTabSheet','XTabSheet1'));
Example1Form.XVBox1:= TXVBox(CreateInterfaceObject(Example1Form,'TXVBox','XVBox1'));
Example1Form.XRadioBtns1:= TXRadioBtns(CreateInterfaceObject(Example1Form,'TXRadioBtns','XRadioBtns1'));



Example1Form.XTabSheet2:= TXTabSheet(CreateInterfaceObject(Example1Form,'TXTabSheet','XTabSheet2'));
Example1Form.XVBox2:= TXVBox(CreateInterfaceObject(Example1Form,'TXVBox','XVBox2'));
Example1Form.XRadioBtns2:= TXRadioBtns(CreateInterfaceObject(Example1Form,'TXRadioBtns','XRadioBtns2'));







